name: Build Nuget Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Pack Aura3D.Core
        run: dotnet pack src/Aura3D.Core -o nugets -c Release
        
      - name: Pack Aura3D.Avalonia
        run: dotnet pack src/Aura3D.Avalonia -o nugets -c Release
      
      - name: Pack Aura3D.Model.AssimpLoader
        run: dotnet pack src/Aura3D.Model.AssimpLoader -o nugets -c Release

      - name: Upload to Nuget
        run: dotnet nuget push "nugets/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
